### ISSUE TITLE
[Submit add-on]: Version Collector test 1

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/addon-datastore-staging#57]
### Download URL

https://github.com/opensourcesys/versionCollector/releases/download/v23.00.065-beta/versionCollector-23.00.065.nvda-addon

### Source URL

https://github.com/opensourcesys/versionCollector/

### Publisher

Luke Davis

### Channel

beta

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by XLTechie** [comment]
@seanbudd you might want to update this fork.

I was trying to test pre-CodeQL behavior, but it seems that the fork is at least somewhat broken, if it doesn't recognize that `beta == beta`.

**Comment by XLTechie** [comment]
Oh, I see, it's a quote-in-quote issue. Even so, not something that users of the repo can fix. It just did the same thing for stable on another issue, so staging is apparently non-functional.

**Comment by seanbudd** [comment]
@XLTechie - I've resynced this fork
